LOCAL_PATH := $(call my-dir)

# WellbeingPrebuilt
include $(CLEAR_VARS)
LOCAL_MODULE := WellbeingPrebuilt
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := app/WellbeingPrebuilt.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# GContacts
include $(CLEAR_VARS)
LOCAL_MODULE := GContacts
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := app/GContacts.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# GDeskClock
include $(CLEAR_VARS)
LOCAL_MODULE := GDeskClock
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := app/GDeskClock.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# GDialer
include $(CLEAR_VARS)
LOCAL_MODULE := GDialer
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := app/GDialer.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# GMessaging
include $(CLEAR_VARS)
LOCAL_MODULE := GMessaging
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := app/GMessaging.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
